language: node_js
node_js: 10
services:
  - mongodb
branches:
  only:
  - master
  - testEnvironment
install:
  - npm ci
  - npm run install
cache:
  directories:
    - node_modules
    - client/node_modules

